diabete_glycemie:
    resource: "@DiabeteBundle/Controller/GlycemieController.php"
    type:     annotation

diabete:
    resource: "@DiabeteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
      _locale: en|fr


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"