diabete_helper_glycemie:
    resource: "@DiabeteHelperBundle/Resources/config/routing/glycemie.yml"
    prefix:   /glycemie

diabete_helper_homepage:
    path:     /
    defaults: { _controller: DiabeteHelperBundle:Default:index }
    methods:  GET

statistiques:
    path:     /stats/
    defaults: { _controller: DiabeteHelperBundle:Statistiques:index }
    methods:  [GET, POST]
